-- Inserting data into the widget & gadget database

-- Widgets
--  id is generated by database (description, price, gears, sprockets)
insert into widgets (description, price, gears, sprockets) values ('Low Impact Widget', 12.99, 2, 3);
insert into widgets (description, price, gears, sprockets) values ('Medium Impact Widget', 42.99, 5, 5);
insert into widgets (description, price, gears, sprockets) values ('High Impact Widget', 89.99, 10, 8);

-- Gadgets
--  id is generated by database (description, price, cylinders)
insert into gadgets (description, price, cylinders) values ('Two Cylinder Gadget', 19.99, 2); 
insert into gadgets (description, price, cylinders) values ('Four Cylinder Gadget', 29.99, 4); 
insert into gadgets (description, price, cylinders) values ('Eight Cylinder Gadget', 49.99, 8); 


-- Commit
commit;