-- Schema definition for the widgets and gadgets

-- Drop the tables if they exist
drop table widgets if exists;
drop table gadgets if exists;

-- Widgets
create table widgets (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, 
  description varchar(45), 
  price numeric(6,2), 
  gears integer, 
  sprockets integer
);

-- Gadgets
create table gadgets (
  id integer  GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, 
  description varchar(45), 
  price numeric(6,2), 
  cylinders integer
);

